import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingNavbar } from "./modules/common/components/floating-navbar";
import { navItems } from "./constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${inter.className} max-w-6xl mx-auto flex flex-col min-h-screen`}
        >
          <FloatingNavbar navItems={navItems} />
          {children}
        </main>
      </body>
    </html>
  );
}
